/** @type {import('eslint').Linter.RulesRecord} */
export const commonRules = {
  "complexity": ["warn", { "max": 10 }],
  "default-case": "warn",
  "eqeqeq": "error",
  "no-empty-function": "warn",
  "no-return-await": "warn",
  "no-script-url": "error",
  "no-self-compare": "error",
  "no-throw-literal": "warn",
  "no-unmodified-loop-condition": "error",
  "no-unused-expressions": "warn",
  "no-useless-return": "warn",
  "require-await": "warn",
  "no-use-before-define": "error",
  "camelcase": "warn",
  "max-depth": ["warn", { "max": 3 }],
  "max-lines": ["warn", { "max": 300, "skipBlankLines": true, "skipComments": true }],
  "max-nested-callbacks": "warn",
  "max-params": ["warn", { "max": 3 }],
  "max-statements": ["warn", { "max": 10 }],
  "no-lonely-if": "warn",
  "no-multiple-empty-lines": ["warn", { "max": 1, "maxEOF": 1, "maxBOF": 0 }],
  "@typescript-eslint/explicit-function-return-type": "warn",
  "@typescript-eslint/no-explicit-any": "warn",
};
